# Generated by Django 3.2.3 on 2021-05-28 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(max_length=100, unique=True)),
                ('classificacao_autor', models.CharField(choices=[('a', 'Diamante'), ('b', 'Ouro'), ('c', 'Prata')], default='c', max_length=1)),
                ('foto_autor', models.ImageField(blank=True, null=True, upload_to='')),
                ('usuario_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_postagem', models.CharField(max_length=100, unique=True)),
                ('resumo_postagem', models.TextField(max_length=400)),
                ('corpo_postagem', models.TextField()),
                ('data_postagem', models.DateTimeField(auto_now=True)),
                ('atualizacao_postagem', models.DateTimeField(auto_now_add=True, null=True)),
                ('autor_postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appapi.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao_log', models.TextField(editable=False)),
                ('data_log', models.DateTimeField(auto_now=True)),
                ('usuario_log', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
